set(KOBOLD_SOURCES
src/cafstream.cpp
src/defparser.cpp
src/i18n.cpp
src/keyboard.cpp
src/kstring.cpp
src/list.cpp
src/log.cpp
src/multitouchcontroller.cpp
src/network.cpp
src/oggstream.cpp
src/parallelprocess.cpp
src/sndfx.cpp
src/sound.cpp
src/soundstream.cpp
src/target.cpp
src/timer.cpp
src/userinfo.cpp
)

set(KOBOLD_HEADERS
src/cafstream.h
src/defparser.h
src/i18n.h
src/keyboard.h
src/keycodes.h
src/kstring.h
src/list.h
src/log.h
src/multitouchcontroller.h
src/network.h
src/oggstream.h
src/parallelprocess.h
src/platform.h
src/sndfx.h
src/sound.h
src/soundstream.h
src/target.h
src/timer.h
src/userinfo.h
)


